version: "3.9"
services:
  web:
    container_name: universal_auto_web
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
      - "44300:44300"
    command: honcho start
    volumes:
      - .:/app

    environment:
      TELEGRAM_TOKEN: <add Your telegram token here>
      UBER_NAME: 
      UBER_PASSWORD: 
      BOLT_NAME: 
      BOLT_PASSWORD: 
      UKLON_NAME: 
      UKLON_PASSWORD:
      REDIS_URL: redis://redis
      DB_HOST: postgres
      POSTGRES_DB: "universal_auto_dev"
      POSTGRES_USER: "universal_auto_dev"
      POSTGRES_PASSWORD: "pass"
      SECRET_KEY:
      UDP_IP: 0.0.0.0
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis

  redis:
    container_name: universal_auto_redis
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  postgres:
    container_name: universal_auto_postgres
    image: postgres:13.8
    environment:
      POSTGRES_DB: "universal_auto_dev"
      POSTGRES_USER: "universal_auto_dev"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U universal_auto_dev -d universal_auto_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  pgadmin:
    container_name: universal_auto_pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "universal_auto_dev@example.com"
      PGADMIN_DEFAULT_PASSWORD: "universal_auto_dev"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
